name: planets
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  get_it: ^7.6.0
  json_annotation: ^4.8.1
  fimber: ^0.6.6
  http: ^1.0.0
  build_runner: ^2.4.4
  rxdart: ^0.27.7
  intl: ^0.17.0
  collection: ^1.17.1
  dio: ^5.1.2

dev_dependencies:
  json_serializable: ^6.6.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans/DMSans-Regular.ttf
          weight: 400
        - asset: fonts/DMSans/DMSans-Italic.ttf
          style: italic          
          weight: 400
        - asset: fonts/DMSans/DMSans-Medium.ttf
          weight: 500
        - asset: fonts/DMSans/DMSans-MediumItalic.ttf
          style: italic          
          weight: 500
        - asset: fonts/DMSans/DMSans-Bold.ttf
          weight: 700
        - asset: fonts/DMSans/DMSans-BoldItalic.ttf
          style: italic          
          weight: 700
